// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// import { application } from "./application"

// import CommentReplyController from "./comment_reply_controller"
// application.register("comment-reply", CommentReplyController)

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)


import { Application } from "@hotwired/stimulus"

import HelloController from "./hello_controller"
import CommentReplyController from "./comment_reply_controller"



window.Stimulus = Application.start()
Stimulus.register("hello", HelloController)
Stimulus.register("comment-reply", CommentReplyController)
