// This file is auto-generated by ./bin/rails view_controller:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewConstroller

import { application } from "./application"

import CommentReplyController from "./comment_reply_controller"
application.register("comment-reply", CommentReplyController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
