// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { Autocomplete } from "stimulus-autocomplete"

import CommentReplyController from "./comment_reply_controller"
application.register("comment-reply", CommentReplyController)

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import RatingController from "./rating_controller"
application.register("rating", RatingController)

application.register("autocomplete", Autocomplete)

