default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres 
  password: 12345678
  pool: 5

development:
  <<: *default
  database: alto_consejo_development


test:
  <<: *default
  database: alto_consejo_test













