import('./sidebar/jquery-3.3.1.min');
import('./sidebar/jquery-migrate-3.0.0.min');
// import('./sidebar/jquery.backstretch');
import('./sidebar/jquery.backstretch.min');
import('./sidebar/jquery.mCustomScrollbar.concat.min');
// import('./sidebar/jquery.waypoints');
import('./sidebar/scripts_index');
import('./sidebar/scripts');
// import('./sidebar/wow');
import('./sidebar/wow.min');
import('./sidebar/jquery.waypoints.min');
// import('./sidebar/waypoints');
import('./sidebar/waypoints.min');